model:
  type: GCN
  kwargs:
    feature_dim: 0
    depth: 4
    hidden_dim: 600
    dropout_rate: 2.0e-3
    augments_dim: 0

    initializer:
      gc:
        method: thomas
    
    criterion_cfg:
      type: L1
      loss_weight: 1.0


trainer:
  epochs: 250
  step_on_val_loss_epoch: 20
  optimizer:
    type: AdamW
    kwargs:
      lr: 4.0e-4
      weight_decay: 5.0e-4
  lr_scheduler:
    type: ReduceLROnPlateau
    kwargs:
      mode: min
      factor: 0.5
      patience: 10
      threshold: 0.01
      verbose: True
  
train:
  leeways: 1
test:
  leeways: [0.01, 0.05, 0.1, 0.2]

data:
    #aug_file_path: '../../datasets/flops.pickle'
  batch_size: 1
  train:
    meta_file_path: '../../datasets/desktop-gpu-gtx-1080ti-fp32-train.pickle'
  val:
    meta_file_path: '../../datasets/desktop-gpu-gtx-1080ti-fp32-val.pickle'
    shuffle: False
  test:
    meta_file_path: '../../datasets/desktop-gpu-gtx-1080ti-fp32-test.pickle'
    shuffle: False
